Repository 2024-Team-Techeer-Salon/Moitda-Frontend, pull requests merged in 2024-06, with the labels that each got.

#53 [feat] 키워드 검색 기능 구현
  src/api/search.ts
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/not-found.tsx
  src/app/search/[keyword]/Body.tsx
  src/app/search/[keyword]/Distance.tsx
  src/app/search/[keyword]/Latest.tsx
  src/app/search/[keyword]/page.tsx
  src/app/search/category/[keyword]/Body.tsx
  src/app/search/category/[keyword]/Distance.tsx
  src/app/search/category/[keyword]/Latest.tsx
  src/app/search/category/[keyword]/page.tsx
  src/app/search/page.tsx
Labels: 🚀 Feat

#55 [feat] 마이페이지 기능 구현
  Dockerfile
  next.config.mjs
  src/api/check.ts
  src/api/user.ts
  src/app/account/Banner.tsx
  src/app/account/Classification.tsx
  src/app/account/CreatedComponent.tsx
  src/app/account/JoinedComponent.tsx
  src/app/account/MannerBar.tsx
  src/app/account/PostCard.tsx
  src/app/account/Profile.tsx
  src/app/account/[userIdParam]/Classification.tsx
  src/app/account/[userIdParam]/Profile.tsx
  src/app/account/[userIdParam]/page.tsx
  src/app/account/page.tsx
  src/app/components/Header.tsx
  src/app/components/Icon.tsx
  src/app/components/MannerStatBar.tsx
  src/app/components/Post.tsx
  src/app/home/Latest.tsx
  src/app/layout.tsx
  src/app/posts/page.tsx
  src/app/search/page.tsx
  src/types/account.ts
  src/types/component.ts
  src/types/post.ts
  src/util/utilFunction.ts
Labels: ⛑️ Build, 🚀 Feat

#57 [feat] 메인페이지 기능구현 완료
  package.json
  src/api/axios.config.ts
  src/api/meetings.ts
  src/api/nearMeeting.ts
  src/app/components/Post.tsx
  src/app/home/Body.tsx
  src/app/home/Distance.tsx
  src/app/home/Header.tsx
  src/app/home/Latest.tsx
  src/app/home/page.tsx
  src/app/posts/page.tsx
  src/app/signup/page.tsx
  src/types/post.ts
  src/util/category.json
  yarn.lock
Labels: 🚀 Feat

#58 [feat] 리뷰 기능 구현
  src/api/meetings.ts
  src/app/account/[userIdParam]/page.tsx
  src/app/home/Body.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/meeting/[meetingParam]/Participants.tsx
  src/app/review/[reviewParam]/page.tsx
  src/app/review/page.tsx
  src/app/search/page.tsx
  src/types/meeting.ts
Labels: 🚀 Feat

#62 [design] 다크모드 시 라이트모드 디자인으로 적용되도록 디자인 등
  src/app/components/Icon.tsx
  src/app/components/InfiniteScroll.tsx
  src/app/components/MannerStatBar.tsx
  src/app/components/Post.tsx
  src/app/home/Body.tsx
  src/app/layout.tsx
  src/app/meeting/[meetingParam]/MeetingHeader.tsx
  src/app/posts/page.tsx
  src/app/signup/page.tsx
  src/app/styles/globals.css
Labels: 🎨 Design

#64 [feat] 채팅방 삭제 기능 구현
  src/api/chat.ts
  src/app/meeting/[meetingParam]/MeetingHeader.tsx
Labels: 🚀 Feat

#71 [chore] ci.yml 완성 및 로컬 테스트 완료
  .github/workflows/CI.yml
  .gitignore
Labels: 🧭 Chore
