Repository 2024-Team-Techeer-Salon/Moitda-Frontend, pull requests merged in 2024-05, with the labels that each got.

#25 design : 기본정보입력 페이지 퍼블리싱
  src/app/basicinfo/page.tsx
Labels: 🎨 Design

#28 [design] 채팅 페이지 퍼블리싱 완료
  next.config.mjs
  src/app/chat/ChatList.tsx
  src/app/chat/ChatWindow.tsx
  src/app/chat/page.tsx
  src/app/components/Footer.tsx
  src/app/page.tsx
  src/app/styles/globals.css
  src/types/chat.ts
Labels: 🎨 Design

#26 [design] 카테고리 검색결과 페이지 퍼블리싱 완료
  src/app/search/category/[keyword]/Body.tsx
  src/app/search/category/[keyword]/Distance.tsx
  src/app/search/category/[keyword]/Latest.tsx
  src/app/search/category/[keyword]/page.tsx
Labels: 🎨 Design

#35 [chore] API 연결 개발 환경 세팅
  package.json
  src/api/axios.config.ts
  src/api/sample.ts
  src/app/cookies.tsx
  yarn.lock
Labels: 🧭 Chore, 🚀 Feat

#32 [design/#18] 후기페이지 퍼블리싱 완료
  src/app/page.tsx
  src/app/review/page.tsx
Labels: 🎨 Design

#38 소셜 로그인 및 기본정보입력 페이지 기능구현 완료
  src/api/auth.ts
  src/api/axios.config.ts
  src/api/user.ts
  src/app/auth/[loginType]/page.tsx
  src/app/basicinfo/page.tsx
  src/app/login/Google.tsx
  src/app/login/Kakao.tsx
  src/app/login/Naver.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  yarn.lock
Labels: 🚀 Feat

#45 [feat] 모임 상세 기능 조회 기능 구현
  next.config.mjs
  public/category.json
  src/api/kakao.ts
  src/api/meetings.ts
  src/api/sample.ts
  src/app/auth/[loginType]/page.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/components/Post.tsx
  src/app/home/Latest.tsx
  src/app/meeting/[meetingParam]/BannerImage.tsx
  src/app/meeting/[meetingParam]/MeetingHeader.tsx
  src/app/meeting/[meetingParam]/Participants.tsx
  src/app/meeting/[meetingParam]/page.tsx
  src/app/meetingdetail/page.tsx
  src/app/posts/page.tsx
  src/app/signup/page.tsx
  src/app/styles/globals.css
  src/types/meeting.ts
  src/types/post.ts
  src/util/category.json
  src/util/utilFunction.ts
Labels: 🚀 Feat

#47 [feat] 웹 전체 반응, 적응형 적용 완료
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/components/Post.tsx
  src/app/home/Body.tsx
  src/app/home/Distance.tsx
  src/app/home/Header.tsx
  src/app/home/Latest.tsx
  src/app/home/page.tsx
  src/app/login/Google.tsx
  src/app/login/Kakao.tsx
  src/app/login/Naver.tsx
  src/app/login/page.tsx
  src/app/posts/page.tsx
  src/app/search/[keyword]/Body.tsx
  src/app/search/[keyword]/Distance.tsx
  src/app/search/[keyword]/page.tsx
  src/app/signup/page.tsx
Labels: 🚀 Feat

#51 [feat] 404에러 커스텀
  src/app/404error/page.tsx
  src/app/components/Footer.tsx
  src/app/not-found.tsx
  tailwind.config.ts
Labels: 🚀 Feat
