Repository 2024-Team-Techeer-Salon/Moitda-Frontend, pull requests merged in 2024-07, with the labels that each got.

#80 [build] main update
  .github/workflows/CI.yml
  .gitignore
  src/api/auth.ts
  src/api/axios.config.ts
  src/api/chat.ts
  src/api/check.ts
  src/api/kakao.ts
  src/api/meetings.ts
  src/api/nearMeeting.ts
  src/api/search.ts
  src/api/user.ts
  src/app/account/[userIdParam]/Classification.tsx
  src/app/account/[userIdParam]/Profile.tsx
  src/app/account/[userIdParam]/page.tsx
  src/app/auth/[loginType]/page.tsx
  src/app/chat/ChatList.tsx
  src/app/components/Header.tsx
  src/app/cookies.tsx
  src/app/home/Body.tsx
  src/app/layout.tsx
  src/app/meeting/[meetingParam]/MeetingHeader.tsx
  src/app/meeting/[meetingParam]/page.tsx
  src/app/not-found.tsx
  src/app/posts/page.tsx
  src/app/review/[reviewParam]/page.tsx
  src/app/search/page.tsx
  src/types/meeting.ts
  src/types/post.ts
  yarn.lock
Labels: ⛑️ Build

#76 fix : dockerfile 수정
  Dockerfile
Labels: 🏷 Fix

#81 [Feat/#36] 채팅 기능 구현완료
  .eslintrc.json
  package.json
  src/api/chat.ts
  src/api/user.ts
  src/app/chat/ChatList.tsx
  src/app/chat/ChatWindow.tsx
  src/app/home/Body.tsx
  src/app/signup/page.tsx
  src/types/chat.ts
  yarn.lock
Labels: 🚀 Feat
